DROP TABLE "PRICER".PRICE_DETAILS;
DROP TABLE "PRICER".STORE_PRICE;
DROP TABLE "PRICER".PRODUCT;
DROP TABLE "PRICER".STORE;




CREATE TABLE "PRICER".PRODUCT (
PRODUCT_ID INTEGER UNIQUE,
PRODUCT_NAME VARCHAR(100),
PRODUCT_DESCRIPTION  VARCHAR(1000),
BASE_PRICE NUMERIC,
CREATED_DATE DATE
);

CREATE TABLE "PRICER".STORE (
STORE_ID INTEGER UNIQUE,
STORE_NAME VARCHAR(100),
STORE_DESCRIPTION  VARCHAR(1000),
CREATED_DATE DATE
);

CREATE TABLE "PRICER".STORE_PRICE (
PRICE_ID INTEGER UNIQUE,
STORE_ID INTEGER,
PRODUCT_ID INTEGER,
CREATED_DATE DATE,
FOREIGN KEY (STORE_ID) REFERENCES "PRICER".STORE(STORE_ID),
FOREIGN KEY (PRODUCT_ID) REFERENCES "PRICER".PRODUCT(PRODUCT_ID)
);

CREATE TABLE "PRICER".PRICE_DETAILS (
DETAILS_ID INTEGER,
PRODUCT_ID INTEGER,
AVERAGE_STORE_PRICE NUMERIC,
IDEAL_STORE_PRICE NUMERIC,
LOWEST_PRICE_ID INTEGER,
HIGHEST_PRICE_ID INTEGER,
SAMPLE_SIZE INTEGER,
CREATED_DATE DATE,
FOREIGN KEY (LOWEST_PRICE_ID) REFERENCES "PRICER".STORE_PRICE(PRICE_ID),
FOREIGN KEY (HIGHEST_PRICE_ID) REFERENCES "PRICER".STORE_PRICE(PRICE_ID),
FOREIGN KEY (PRODUCT_ID) REFERENCES "PRICER".PRODUCT(PRODUCT_ID)
);


COMMIT;
